const SYSTEM_CONFIG = {
    soundEnabled: true,
    lastTypingTime: 0,
    typingSoundDelay: 80
};

function playSound(id, volume = 0.3) {
    if (!SYSTEM_CONFIG.soundEnabled) return;
    const sound = document.getElementById(id);
    if (!sound) {
        console.warn(`Sound element #${id} not found in HTML.`);
        return;
    }

    sound.currentTime = 0;
    sound.volume = volume;
    sound.play().catch(() => {});
}

document.addEventListener("DOMContentLoaded", () => {
    const characters = [
        {
            id: 1,
            name: "Naked Snake",
            faction: "fox_unit",
            role: "CIA FOX Unit Operative",
            clearance: 2,
            bio: "The man who would become Big Boss. A disciple of The Boss and an expert in CQC. He famously infiltrated Tselinoyarsk to stop the Shagohod and eliminate his own mentor.",
            quote: "'I'm just a soldier. And always will be.'",
            story: "Before the legend of Big Boss, he was a green operative known as Naked Snake. During Operation Snake Eater, he was forced to kill his mentor, The Boss, to prevent a nuclear war, a task that forever changed his worldview.",
            image: "images/METAL Gear Solid 3_ SNAKE EATER REMAKE.jpg",
            video: "Video/Metal Gear Solid Delta Snake Eater - Grave Scene (Snake Crying) - Savage Slayer (720p, h264).mp4",
            audio: "Audio/Solid_Snake_MGS2_Speech.mp3.wav",
            wiki: "https://metalgear.fandom.com/wiki/Big_Boss"
        },
        {
            id: 2,
            name: "The Boss",
            faction: "cobra_unit",
            role: "The Mother of Special Forces",
            clearance: 2,
            bio: "Legendary soldier who created modern special forces tactics. Mentor to Big Boss and founder of the Cobra Unit. Considered the greatest soldier who ever lived.",
            quote: "'There's only room for one Boss... and one snake.'",
            story: "Created the basics of CQC (Close Quarters Combat). Sacrificed everything for her country, allowing herself to be branded a traitor to maintain world balance. Her will shaped the entire Metal Gear saga.",
            image: "images/metal gear solid delta _ • The Boss.jpg",
            video: "Video/Metal Gear Solid Delta Snake Eater - The Boss Final Boss Fight (PS5 Pro 4K 60FPS) - Boss Fight Database (360p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/The_Boss"
        },
        {
            id: 3,
            name: "Venom Snake",
            faction: "diamond_dogs", 
            role: "The Phantom / Commander of Diamond Dogs",
            clearance: 2,
            bio: "A combat medic who underwent mental and physical reconstruction to serve as a body double for Big Boss. He leads Diamond Dogs with a robotic prosthetic and a shrapnel 'horn' embedded in his skull.",
            quote: "'I'm already a demon. Heaven's not my kind of place anyway.'",
            story: "After the destruction of MSF, he was transformed into a 'Phantom' to draw attention away from the real Big Boss. He built Diamond Dogs and faced Skull Face, eventually accepting his role as part of the legend.",
            image: "images/Metal Gear Solid V_ The Phantom Pain _ Big Boss!.jpg",
            video: "Video/INVISIBLE  MGSV  TRIBUTE - Doomdy (720p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/Venom_Snake"
        },
        {
            id: 4,
            name: "Major Zero",
            faction: "fox_unit",
            role: "Founder of Cipher / The Patriots",
            clearance: 2,
            bio: "Former SAS member and commander of the FOX Unit. Originally Naked Snake's commanding officer, he eventually became his greatest ideological rival, seeking to control the world through information.",
            quote: "'We'll be the ones to pull the strings. The world will be united under a single will.'",
            story: "Following the death of The Boss, Zero founded the Patriots to realize her vision. However, his obsession with control led to a rift with Big Boss and the eventual creation of the AI network that ruled society.",
            image: "images/ZERO -  Metal Gear Solid 3_ Snake Eater….jpg",
            audio: "Audio/Zero_I_have_found_the_way.wav",
            wiki: "https://metalgear.fancy.com/wiki/Zero"
        },
        {
            id: 5,
            name: "Para-Medic",
            faction: "fox_unit",
            role: "Medical and Biolife Specialist",
            clearance: 4,
            bio: "A movie-obsessed medical specialist who provided support during the Virtuous Mission and Operation Snake Eater. She later became a key founding member of the Patriots.",
            quote: "'Snake, have you ever seen 'Godzilla'? It's a classic!'",
            story: "Known as Dr. Clark in later years, she was responsible for the Les Enfants Terribles cloning project and the cyborg ninja experiments on Gray Fox. Her medical genius shaped the darker side of Patriot history.",
            image: "images/౨ৎ (1).jpg",
            video: "video/paramedic.mp4",
            audio: "audio/voices/paramedic.ogg",
            wiki: "https://metalgear.fandom.com/wiki/Para-Medic"
        },
        {
            id: 6,
            name: "Sigint",
            faction: "foxhound",
            role: "Technical and Weapons Consultant",
            clearance: 2,
            bio: "An expert in high-tech weaponry and equipment. He provided technical support to Naked Snake before eventually becoming the Chief of DARPA.",
            quote: "'I'm a tech man. If it's got a circuit or a trigger, I can tell you how it works.'",
            story: "A brilliant engineer who helped develop the gear used by the FOX unit. As Donald Anderson, he later oversaw the development of Metal Gear REX before being killed during the Shadow Moses incident.",
            image: "images/Sigint.jpg",
            wiki: "https://metalgear.fandom.com/wiki/Sigint"
        },
        {
            id: 7,
            name: "Quiet",
            faction: "diamond_dogs",
            role: "Supernatural Sniper",
            clearance: 2,
            bio: "An elite assassin infected with 'The One Who Covers' parasites. She possesses superhuman speed, strength, and the ability to photosynthesize, but cannot speak without triggering a deadly plague.",
            quote: "(Silence/Humming)",
            story: "Originally sent by XOF to kill Big Boss, she was defeated and joined Diamond Dogs. She eventually sacrificed herself by speaking English to save Venom Snake's life in the Afghan desert.",
            image: "images/Metal Gear Solid V_ The Phantom Pain.jpg",
            wiki: "https://metalgear.fandom.com/wiki/Quiet"
        },
        {
            id: 8,
            name: "Skull Face",
            faction: "xof",
            role: "Commander of XOF",
            clearance: 2,
            bio: "The mysterious, disfigured leader of the XOF strike force. A survivor of a childhood trauma that robbed him of his language and his face, he seeks to destroy the English language with parasites.",
            quote: "'Words can kill. I will give the world its freedom... by taking its speech.'",
            story: "He operated in the shadows of the FOX unit for years. He destroyed Mother Base in 1975 and later attempted to use Sahelanthropus to force the world into a nuclear standoff controlled by his parasites.",
            image: "images/Skull Face (XOF)  _ Metal Gear Solid V The Phantom….jpg",
            video: "Video/Skull Face Intro First Scene — Metal Gear Solid 5 - Gamer Guru (360p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/Skull_Face"
        },
        {
            id: 9,
            name: "The Sorrow",
            faction: "cobra_unit",
            role: "Spirit Medium / Cobra Unit Member",
            clearance: 2,
            bio: "A powerful medium who could summon the dead to aid him in battle. Even in death, his spirit continued to guide and haunt Naked Snake.",
            quote: "'The spirits of those you have killed will follow you forever.'",
            story: "The lover of The Boss and father of Revolver Ocelot. He was killed by The Boss during a mission in 1962, but returned as a ghost to test Snake's resolve during the mission to destroy Groznyj Grad.",
            image: "images/The Sorrow _ Metal Gear Solid ∆_ snake eater.jpg",
            video: "Video/Metal Gear Solid Delta Snake Eater - Full The Sorrow Boss Fight (4K) - Sirloin (360p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/The_Sorrow"
        },
        {
            id: 10,
            name: "The Fury",
            faction: "cobra_unit",
            role: "Pyrotechnics Expert",
            clearance: 2,
            bio: "A former Soviet cosmonaut who suffered horrific burns during a failed atmospheric reentry. He channels his eternal rage through a specialized flame-retardant suit and a powerful flamethrower.",
            quote: "'I've seen the fire of the stars... now you will feel the fire of my hate!'",
            story: "After returning from space, he felt only a constant, burning anger. He joined the Cobra Unit to find a place where his fire could truly consume his enemies.",
            image: "images/The Fury - Metal Gear Solid 3_ Snake Eater….jpg",
            video: "Video/The Fury Introduction - Metal Gear Solid Delta Snake Eater - iamhijak (360p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/The_Fury"
        },
        {
            id: 11,
            name: "The Pain",
            faction: "cobra_unit",
            role: "Hornet Controller",
            clearance: 2,
            bio: "A soldier who controls swarms of 'bullet bees' housed within his own body. He can use them to create shields, weapons, and even clones of himself.",
            quote: "'Taste the sting of my hornets!'",
            story: "A member of the Cobra Unit who fought alongside The Boss in WWII. He can manipulate his bees through pheromones and high-frequency sounds, making him a terrifying forest-dwelling predator.",
            image: "images/ThePainMGSDelta.jpg",
            video: "Video/The Pain MGS3 REMAKE Full Scene - thevoicebox (360p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/The_Pain"
        },
        {
            id: 12,
            name: "The Fear",
            faction: "cobra_unit",
            role: "Stealth and Traps Specialist",
            clearance: 2,
            bio: "An incredibly agile soldier with a double-jointed body and the ability to blend into his surroundings like a chameleon. He uses a specialized crossbow with venom-tipped bolts.",
            quote: "'The fear... I can smell it coming off you in waves!'",
            story: "Known for his terrifying appearance and spider-like movements. He set traps throughout the Graniny Gorki forests to hunt Naked Snake, utilizing his 'stealth camouflage' parasites.",
            image: "images/MGS3 Remastered - The Fear.jpg",
            video: "Video/The Fear MGS3 REMAKE Full Scene - thevoicebox (360p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/The_Fear"
        },
        {
            id: 13,
            name: "Code Talker",
            faction: "diamond_dogs",
            role: "Parasite Specialist / Wise Man",
            clearance: 7,
            bio: "A centenarian Navajo biologist who discovered the secrets of the vocal cord parasites. He survives through a symbiotic relationship with 'The One Who Covers' parasites.",
            quote: "'The words we speak are the chains that bind us to our history.'",
            story: "Forced by Skull Face to develop the vocal cord parasites. He eventually joined Diamond Dogs to help Venom Snake develop a cure for the infection that threatened to wipe out their base.",
            image: "images/Code Talker; a wise man denied his homeland_.jpg",
            wiki: "https://metalgear.fandom.com/wiki/Code_Talker"
        },
        {
            id: 14,
            name: "Colonel Volgin",
            faction: "others",
            role: "GRU Commander / Thunderbolt",
            clearance: 2,
            bio: "A sadistic Soviet Colonel with the ability to manipulate electricity. He sought to use the Philosophers' Legacy to overthrow the Soviet government and spark a new world war.",
            quote: "'Kuwabara... Kuwabara... I'll show you the true power of the Thunderbolt!'",
            story: "The main antagonist of Snake Eater. He commanded the fortress Groznyj Grad and the Shagohod. After his apparent death, his vengeful spirit returned as the 'Man on Fire' in 1984.",
            image: "images/Volgin.jpg",
            video: "Video/Volgin Fires The Nuke MGS3 REMAKE (Full Scene) HD - Manalithy (360p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/Yevgeny_Borisovitch_Volgin"
        },
        {
            id: 15,
            name: "Solid Snake",
            faction: "foxhound",
            role: "Infiltration Specialist",
            clearance: 5,
            bio: "Clone of Big Boss, legendary operative who saved the world multiple times. Known for his cynical outlook and relentless determination. Codenamed 'Iroquois Pliskin' during the Big Shell incident.",
            quote: "'There's no such thing in the world as absolute reality. Most of what they call real is actually fiction. What you think you see is only as real as your brain tells you it is.'",
            story: "Main protagonist of the Metal Gear series. A former Green Beret and FOXHOUND operative who took down Metal Gear multiple times. Despite being a clone destined to die young, he chose his own path and became a legend.",
            image: "images/Solid Snake.jpg",
            video: "video/snake.mp4",
            audio: "audio/voices/snake.ogg",
            wiki: "https://metalgear.fandom.com/wiki/Solid_Snake"
        },
        {
            id: 16,
            name: "Big Boss",
            faction: "others",
            role: "Legendary Soldier / Mercenary Leader",
            clearance: 2,
            bio: "The greatest soldier of the 20th century. Real name John. Veteran of WWII, Vietnam, and numerous Cold War conflicts. Founded both FOXHOUND and Outer Heaven.",
            quote: "'We have no nation, no philosophy, no ideology. We go where we're needed, fighting not for country, not for government, but for ourselves. We need no reason to fight.'",
            story: "Originally known as Naked Snake, he became Big Boss after defeating his mentor, The Boss. Created the concept of the nation-less army and inspired generations of soldiers. His DNA was used to create the Les Enfants Terribles project.",
            image: "images/Old Big Boss at the end of the series.jpg",
            audio: "Audio/Big_Boss_No_Nation.wav",
            wiki: "https://metalgear.fandom.com/wiki/Big_Boss"
        },
        {
            id: 17,
            name: "EVA",
            faction: "others",
            role: "Triple Agent / Spy",
            clearance: 2,
            bio: "Chinese spy who infiltrated the Philosophers and later worked with both the CIA and KGB. Real name unknown. One of the most skilled espionage agents in history.",
            quote: "'The world calls for wetwork, and we answer. No greater good. No just cause.'",
            story: "Posed as a scientist during the Virtuous Mission, she helped Naked Snake defeat The Boss. Later revealed to be a triple agent working for China. Became the lover of both Big Boss and Ocelot at different points in her life.",
            image: "images/౨ৎ.jpg",
            wiki: "https://metalgear.fandom.com/wiki/EVA"
        },
        {
            id: 18,
            name: "Raiden",
            faction: "others",
            role: "Cyborg Ninja/The Patriots",
            clearance: 2,
            bio: "Former child soldier turned elite operative. Initially a rookie during the Big Shell incident, he later becomes the most advanced cyborg ninja in the world.",
            quote: "'I'm no hero. Never was, never will be. I'm just an old killer hired to do some wet work.'",
            story: "Survived the Liberian Civil War as a child. Was manipulated by the Patriots during the Big Shell incident. After being captured and turned into a cyborg, he became a legendary mercenary known as 'Jack the Ripper.'",
            image: "images/— raiden METAL GEAR_.jpg",
            wiki: "https://metalgear.fandom.com/wiki/Raiden"
        },
        {
            id: 19,
            name: "The End",
            faction: "cobra_unit",
            role: "Sniper / Biologist",
            clearance: 2,
            bio: "Centenarian sniper with supernatural abilities. Can photosynthesize and merge with nature. Considered the greatest sniper in history.",
            quote: "'Time is on my side... always.'",
            story: "Over 100 years old, The End fought in both World Wars. Member of the Cobra Unit. His unique biology allows him to go without food or water for weeks. The only enemy that can literally die of old age if the player waits long enough.",
            image: "images/MGS3 Remastered - The End.jpg",
            video: "Video/Metal Gear Solid Delta Snake Eater - Full The End Boss Fight (4K) - Sirloin (360p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/The_End"
        },
        {
            id: 20,
            name: "Meryl Silverburgh",
            faction: "us_army",
            role: "Special Forces Commander",
            clearance: 8,
            bio: "Niece of Colonel Campbell. Started as a rookie during the Shadow Moses incident, eventually becoming commander of Rat Patrol Team 01.",
            quote: "'I fight for what I believe in. Not for a country, not for a flag, but for myself.'",
            story: "Defied her uncle to join FOXHOUND. Survived the Shadow Moses incident and became a highly respected special forces operative. Known for her purple hair and determination to prove herself.",
            image: "images/𝐌𝐞𝐫𝐲𝐥 𝐒𝐢𝐥𝐯𝐞𝐫𝐛𝐮𝐫𝐠𝐡 •ᴍɢs4.jpg",
            video: "video/meryl.mp4",
            audio: "audio/voices/meryl.ogg",
            wiki: "https://metalgear.fandom.com/wiki/Meryl_Silverburgh"
        },
        {
            id: 21,
            name: "Colonel Roy Campbell",
            faction: "us_army",
            role: "Commanding Officer",
            clearance: 2,
            bio: "Veteran commander with decades of experience. Uncle to Meryl Silverburgh. Served in Vietnam and numerous special operations.",
            quote: "'This is no time for hesitation. Make a decision, and live with the consequences.'",
            story: "Commanded FOXHOUND during the Shadow Moses incident. Former lover of The Boss. Despite his tough exterior, cares deeply for his subordinates. One of the few commanders who truly understands the cost of war.",
            image: "images/Colonel Roy Campbell.jpg",
            wiki: "https://metalgear.fandom.com/wiki/Roy_Campbell"
        },
        {
            id: 22,
            name: "Psycho Mantis",
            faction: "foxhound",
            role: "Psychic / Interrogator",
            clearance: 2,
            bio: "Powerful psychic who can read minds and control people. Hates humanity due to childhood trauma.",
            quote: "'I can see into your mind... I know everything about you.'",
            story: "Born with powerful psychic abilities that made him an outcast. Joined FOXHOUND and became Liquid Snake's most dangerous operative. Known for his iconic boss battle where he reads the player's memory card.",
            image: "images/Psycho Mantis ☆.jpg",
            video: "Video/Metal Gear Solid 5 Phantom Pain - Psycho Mantis (MGS5) - DarkSagor (720p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/Psycho_Mantis"
        },
        {
            id: 23,
            name: "Chico Valenciano Libre",
            faction: "MSF",
            role: "Child Soldier / Radio Operator",
            clearance: 9,
            bio: "Young Costa Rican boy rescued by Big Boss. Became a radio operator for the Militaires Sans Frontières.",
            quote: "'I want to be strong, like you. I want to fight.'",
            story: "Survived the Sandinista conflict in Costa Rica. Saved by Big Boss and became his protege. His fate remains one of the series' most tragic stories, showing the cost of war on children.",
            image: "images/┊ ִֶָ𓂃 ࣪˖ ִֶָ ᑕᕼIᑕO ་༘࿐.jpg",
            video: "video/chico.mp4",
            audio: "audio/voices/chico.ogg",
            wiki: "https://metalgear.fandom.com/wiki/Chico"
        },
        {
            id: 24,
            name: "Huey Emmerich",
            faction: "MSF",
            role: "Scientist / Engineer",
            clearance: 2,
            bio: "Brilliant but morally compromised scientist. Father of Hal 'Otacon' Emmerich. Creator of early Metal Gear prototypes.",
            quote: "'Science cannot progress without sacrifice... but some sacrifices are too great.'",
            story: "Designed the first bipedal nuclear weapon carrier. Worked for multiple governments and private organizations. His unethical experiments and personal failures created a legacy of tragedy for his family.",
            image: "images/ꉂ ᕼᑌEY EᗰᗰEᖇIᑕᕼ 𐭩.jpg",
            video: "Video/Metal Gear Solid V The Phantom Pain - Huey Introduction - Generic Gaming (720p, h264).mp4",
            wiki: "https://metalgear.fandom.com/wiki/Huey_Emmerich"
        },
        {
            id: 25,
            name: "Revolver Ocelot",
            faction: "foxhound",
            role: "Interrogation Specialist",
            clearance: 2,
            bio: "Master marksman, strategist, and triple agent. Son of The Boss and a Soviet GRU colonel. The ultimate schemer of the series.",
            quote: "'I'm a revolver... six bullets... more than enough to kill anything that moves.'",
            story: "Played every side against the middle for decades. His loyalty was always to himself and his mother's will. The architect behind the Patriots' downfall. Known for his obsession with revolvers and psychological warfare.",
            image: "images/Revolver Ocelot MGS Delta.jpg",
            video: "Video/Snake Meets Ocelot For The First Time — MGS3 REMAKE (Full Scene & No Commentary) - PythonSelkan (360p, h264).mp4",
            audio: "Audio/TTS_Ocelot_We_Need_Tension.mp3.wav",
            wiki: "https://metalgear.fandom.com/wiki/Revolver_Ocelot"
        },
        {
            id: 26,
            name: "Kazuhira Miller",
            faction: "philanthropy",
            role: "Strategic Advisor / Logistician",
            clearance: 9,
            bio: "Master of logistics, training, and battlefield economics. The man who keeps armies running.",
            quote: "'We're not tools of the government, or anyone else. Fighting was the only thing... the only thing I was good at.'",
            story: "Half-Japanese, half-American soldier who lost everything in the Cold War. Co-founded Militaires Sans Frontières with Big Boss. After losing Mother Base, he dedicated his life to revenge and rebuilding.",
            image: "images/Kaz.jpg",
            video: "video/miller.mp4",
            audio: "audio/voices/miller.ogg",
            wiki: "https://metalgear.fandom.com/wiki/Kazuhira_Miller"
        },
                {
            id: 27,
            name: "Otacon",
            faction: "philanthropy",
            role: "Scientist / Engineer",
            clearance: 9,
            bio: "Brilliant engineer with a strong moral compass. Son of Huey Emmerich. Creator of Metal Gear REX.",
            quote: "'Science is about finding the truth. Even if that truth is ugly.'",
            story: "Overcame his family's legacy to become a force for good. Co-founded Philanthropy with Solid Snake to stop Metal Gear proliferation. Known for his technical genius and social anxiety.",
            image: "images/Otacon Metal Gear Solid 4.jpg",
            video: "video/otacon.mp4",
            audio: "audio/voices/otacon.ogg",
            wiki: "https://metalgear.fandom.com/wiki/Otacon"
        },
        {
            id: 28,
            name: "Liquid Snake",
            faction: "foxhound",
            role: "Terrorist Leader",
            clearance: 2,
            bio: "Twin brother of Solid Snake. Dominant genes from Big Boss. Led the FOXHOUND rebellion on Shadow Moses.",
            quote: "'We're not just clones, brother. We're the future. And you're the past.'",
            story: "Believed he inherited recessive genes from Big Boss, driving his inferiority complex and hatred for his brother. Masterminded the Shadow Moses incident to obtain Metal Gear REX and declare war on the Patriots.",
            image: "images/Liquid Snake Metal Gear Solid 1.jpg",
            audio: "Audio/Liquid_Snake_World_Gone_Soft.wav",
            wiki: "https://metalgear.fandom.com/wiki/Liquid_Snake"
        },
        {
            id: 29,
            name: "Sniper Wolf",
            faction: "foxhound",
            role: "Sniper",
            clearance: 2,
            bio: "Kurdish sniper saved by Big Boss. Considered the best sniper in FOXHOUND after The End.",
            quote: "'I live for the hunt. The moment when the crosshairs align... and time stops.'",
            story: "Orphaned during the Gulf War and rescued by Big Boss. Devoted to him completely. Her tragic love story with Otacon highlights the human cost of war.",
            image: "images/Sniper Wolf  Metal Gear Solid 1.jpg",
            wiki: "https://metalgear.fandom.com/wiki/Sniper_Wolf"
        },
        